### ISSUE TITLE
Default behavior pulls too few logs

### ISSUE THREAD

**Issue by cardonator** [github/ghec-audit-log-cli#27]
**Describe the bug**
The default behavior of this project pulls only organization level logs and no logs associated with the repos within an organization. In our case, that limits the usefulness of relying on the V4 API integration because it's missing many logs that we need to have available for our external audits. Switching to the V3 API works.

**To Reproduce**
1. `ghec-audit-log-cli -t "PAT" -o "org-id" -p -l 5`
2. Review results
3. In our well established org, see many events with `"__typename": "OrgAddMemberAuditEntry",` and no repo level events

**Expected behavior**
Expecting to see events taking place on the repo level, especially changes to settings on individual repos. For backstory, we have many audit relevant repositories that must have the `Include Administrators` option set on protected branches. We need to be able to audit logs that indicate this setting has been changed.

**Desktop (please complete the following information):**
 - OS: Linux CLI

**Comment by droidpl** [comment]
@cardonator Apologies as this issue slipped over my inbox. .

What you are experiencing is a limitation on the API, not the CLI. The V4 API is not covering all the events that you actually see in the audit log when checking this over the UI. This happens because maintaining the API for V4 with all the different models and events is really hard, and we will drop it at some point in time. 

Moving forward the API that is meant to be used for Audit logs is the V3, so you did the right thing. 

Unfortunately what you are mentioning here is something we cannot address within the scope of the CLI, so I will proceed closing it.

**Comment by cardonator** [comment]
Oh that's good news then. Thanks for clarifying!
